services:
  db:
    image: postgres:17-alpine
    container_name: promotions_db
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=promotions_db
    volumes:
      - ./db/promotions_db.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: promotions_frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
